#### 1)

In [29]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
mnist = datasets.load_digits()

#### 2)

In [3]:
X = pd.DataFrame(np.array(mnist.data))

In [4]:
y = pd.DataFrame(mnist.target)

#### 3)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

#### 4)

In [26]:
model = LogisticRegression()
model.fit(X_train, y_train)
predict = model.predict(X_test)

#### 5)

In [10]:
kfold = model_selection.KFold(n_splits=10, random_state=7)

In [17]:
res1 = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')

In [18]:
print("%.3f"%(res1.mean()*100))

95.172


#### 6)

In [23]:
res2 = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='neg_log_loss')
print(res2.mean()*100)

-25.3925903368


#### 7)

In [31]:
res3 = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='r2')
print(res3.mean()*100)

86.5725244127


#### 8)

In [34]:
res4 = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='neg_mean_absolute_error')
print(res4.mean()*100)

-20.2089552239


#### 9)

In [32]:
res5 = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='neg_mean_squared_error')
print(res5.mean()*100)

-111.919292427


#### 10)

In [28]:
matrix = confusion_matrix(y_test, predict)
print matrix

[[42  0  0  0  1  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  1  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 44  0  1  0  0  1  0]
 [ 0  1  0  0 54  0  0  0  0  0]
 [ 0  0  1  0  0 56  0  0  1  1]
 [ 0  0  0  0  0  1 44  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  1]
 [ 0  1  0  0  0  1  0  0 36  0]
 [ 0  0  0  0  0  0  0  0  3 45]]


#### 11)

In [30]:
report = classification_report(y_test, predict)
print report

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        43
          1       0.95      0.97      0.96        37
          2       0.97      1.00      0.99        38
          3       1.00      0.96      0.98        46
          4       0.98      0.98      0.98        55
          5       0.95      0.95      0.95        59
          6       1.00      0.98      0.99        45
          7       1.00      0.98      0.99        41
          8       0.86      0.95      0.90        38
          9       0.96      0.94      0.95        48

avg / total       0.97      0.97      0.97       450

